name: Publish Python Package to PyPI

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: poetry install

  build:
    runs-on: ubuntu-latest
    needs: install

    steps:
    - name: Build the package
      run: poetry build

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Publish to PyPI
      env:
        USERNAME: __token__
        PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: poetry publish --username $USERNAME --password $PASSWORD
